/*
 * Yeti 2, NesC development in Eclipse.
 * Copyright (C) 2009 ETH Zurich
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Web:  http://tos-ide.ethz.ch
 * Mail: tos-ide@tik.ee.ethz.ch
 */

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 20 10:42:35 CEST 2008
//----------------------------------------------------

package tinyos.yeti.preprocessor.expression;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int GREATER_EQ = 17;
  public static final int MOD = 6;
  public static final int BIT_AND = 9;
  public static final int AND = 10;
  public static final int QUESTION = 25;
  public static final int DEFINED = 24;
  public static final int PLUS = 2;
  public static final int CLOSE = 21;
  public static final int OR = 8;
  public static final int CHARACTER = 29;
  public static final int DIVISION = 5;
  public static final int NOT = 11;
  public static final int IDENTIFIER = 28;
  public static final int ERROR = 30;
  public static final int SHIFT_RIGHT = 22;
  public static final int GREATER = 16;
  public static final int SHIFT_LEFT = 23;
  public static final int COLON = 26;
  public static final int EOF = 0;
  public static final int BIT_OR = 7;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int BIT_REVERSE = 13;
  public static final int LESS_EQ = 19;
  public static final int EQ = 14;
  public static final int INTEGER = 27;
  public static final int XOR = 12;
  public static final int OPEN = 20;
  public static final int NEQ = 15;
  public static final int LESS = 18;
}

