/*
 * Yeti 2, NesC development in Eclipse.
 * Copyright (C) 2009 ETH Zurich
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Web:  http://tos-ide.ethz.ch
 * Mail: tos-ide@tik.ee.ethz.ch
 */

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 24 09:18:36 CET 2009
//----------------------------------------------------

package tinyos.yeti.preprocessor.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int K_IFNDEF = 21;
  public static final int K_IF = 19;
  public static final int VARARG = 11;
  public static final int SHARP = 7;
  public static final int CLOSE = 14;
  public static final int SMALLER = 10;
  public static final int IDENTIFIER = 12;
  public static final int K_ELIF = 23;
  public static final int K_IFDEF = 20;
  public static final int CONCAT = 8;
  public static final int GREATER = 9;
  public static final int K_ENDIF = 24;
  public static final int K_LINE = 26;
  public static final int K_DEFINE = 16;
  public static final int QUOTE = 4;
  public static final int K_ERROR = 29;
  public static final int COMMA = 15;
  public static final int K_INCLUDE = 25;
  public static final int EOF = 0;
  public static final int K_DEFINED = 17;
  public static final int NEWLINE = 3;
  public static final int error = 1;
  public static final int K_ELSE = 22;
  public static final int K_WARNING = 28;
  public static final int TEXT = 5;
  public static final int OPEN = 13;
  public static final int K_PRAGMA = 27;
  public static final int K_UNDEF = 18;
  public static final int MASKED_QUOTE = 6;
  public static final int WHITESPACE = 2;
}

