/* The following code was generated by JFlex 1.4.1 on 20.08.08 10:42 */

package tinyos.yeti.preprocessor.expression;

import tinyos.yeti.preprocessor.parser.*;
import java_cup.runtime.*;

/**
 * This class reads a single expression and searches tokens in the expression.
 */

class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\16\1\14\1\16\1\16\1\17\22\0\1\16\1\26\1\45"+
    "\3\0\1\25\1\12\1\34\1\35\1\22\1\20\1\0\1\21\1\10"+
    "\1\23\1\4\7\15\2\3\1\37\1\0\1\33\1\31\1\32\1\36"+
    "\1\0\3\6\1\11\1\6\1\11\5\1\1\7\10\1\1\7\5\1"+
    "\1\0\1\13\1\0\1\27\1\1\1\0\3\6\1\40\1\41\1\42"+
    "\2\1\1\43\2\1\1\7\1\1\1\44\6\1\1\7\2\1\1\5"+
    "\2\1\1\0\1\24\1\0\1\30\6\0\1\16\44\0\1\1\12\0"+
    "\1\1\4\0\1\1\5\0\27\1\1\0\37\1\1\0\u013f\1\31\0"+
    "\162\1\4\0\14\1\16\0\5\1\11\0\1\1\213\0\1\1\13\0"+
    "\1\1\1\0\3\1\1\0\1\1\1\0\24\1\1\0\54\1\1\0"+
    "\46\1\1\0\5\1\4\0\202\1\10\0\105\1\1\0\46\1\2\0"+
    "\2\1\6\0\20\1\41\0\46\1\2\0\1\1\7\0\47\1\110\0"+
    "\33\1\5\0\3\1\56\0\32\1\5\0\13\1\25\0\12\2\4\0"+
    "\2\1\1\0\143\1\1\0\1\1\17\0\2\1\7\0\2\1\12\2"+
    "\3\1\2\0\1\1\20\0\1\1\1\0\36\1\35\0\3\1\60\0"+
    "\46\1\13\0\1\1\u0152\0\66\1\3\0\1\1\22\0\1\1\7\0"+
    "\12\1\4\0\12\2\25\0\10\1\2\0\2\1\2\0\26\1\1\0"+
    "\7\1\1\0\1\1\3\0\4\1\3\0\1\1\36\0\2\1\1\0"+
    "\3\1\4\0\12\2\2\1\23\0\6\1\4\0\2\1\2\0\26\1"+
    "\1\0\7\1\1\0\2\1\1\0\2\1\1\0\2\1\37\0\4\1"+
    "\1\0\1\1\7\0\12\2\2\0\3\1\20\0\11\1\1\0\3\1"+
    "\1\0\26\1\1\0\7\1\1\0\2\1\1\0\5\1\3\0\1\1"+
    "\22\0\1\1\17\0\2\1\4\0\12\2\25\0\10\1\2\0\2\1"+
    "\2\0\26\1\1\0\7\1\1\0\2\1\1\0\5\1\3\0\1\1"+
    "\36\0\2\1\1\0\3\1\4\0\12\2\1\0\1\1\21\0\1\1"+
    "\1\0\6\1\3\0\3\1\1\0\4\1\3\0\2\1\1\0\1\1"+
    "\1\0\2\1\3\0\2\1\3\0\3\1\3\0\10\1\1\0\3\1"+
    "\55\0\11\2\25\0\10\1\1\0\3\1\1\0\27\1\1\0\12\1"+
    "\1\0\5\1\46\0\2\1\4\0\12\2\25\0\10\1\1\0\3\1"+
    "\1\0\27\1\1\0\12\1\1\0\5\1\3\0\1\1\40\0\1\1"+
    "\1\0\2\1\4\0\12\2\25\0\10\1\1\0\3\1\1\0\27\1"+
    "\1\0\20\1\46\0\2\1\4\0\12\2\25\0\22\1\3\0\30\1"+
    "\1\0\11\1\1\0\1\1\2\0\7\1\72\0\60\1\1\0\2\1"+
    "\14\0\7\1\11\0\12\2\47\0\2\1\1\0\1\1\2\0\2\1"+
    "\1\0\1\1\2\0\1\1\6\0\4\1\1\0\7\1\1\0\3\1"+
    "\1\0\1\1\1\0\1\1\2\0\2\1\1\0\4\1\1\0\2\1"+
    "\11\0\1\1\2\0\5\1\1\0\1\1\11\0\12\2\2\0\2\1"+
    "\42\0\1\1\37\0\12\2\26\0\10\1\1\0\42\1\35\0\4\1"+
    "\164\0\42\1\1\0\5\1\1\0\2\1\25\0\12\2\6\0\6\1"+
    "\112\0\46\1\12\0\51\1\7\0\132\1\5\0\104\1\5\0\122\1"+
    "\6\0\7\1\1\0\77\1\1\0\1\1\1\0\4\1\2\0\7\1"+
    "\1\0\1\1\1\0\4\1\2\0\47\1\1\0\1\1\1\0\4\1"+
    "\2\0\37\1\1\0\1\1\1\0\4\1\2\0\7\1\1\0\1\1"+
    "\1\0\4\1\2\0\7\1\1\0\7\1\1\0\27\1\1\0\37\1"+
    "\1\0\1\1\1\0\4\1\2\0\7\1\1\0\47\1\1\0\23\1"+
    "\16\0\11\2\56\0\125\1\14\0\u026c\1\2\0\10\1\12\0\32\1"+
    "\5\0\113\1\25\0\15\1\1\0\4\1\16\0\22\1\16\0\22\1"+
    "\16\0\15\1\1\0\3\1\17\0\64\1\43\0\1\1\4\0\1\1"+
    "\3\0\12\2\46\0\12\2\6\0\130\1\10\0\51\1\127\0\35\1"+
    "\51\0\12\2\36\1\2\0\5\1\u038b\0\154\1\224\0\234\1\4\0"+
    "\132\1\6\0\26\1\2\0\6\1\2\0\46\1\2\0\6\1\2\0"+
    "\10\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0\37\1\2\0"+
    "\65\1\1\0\7\1\1\0\1\1\3\0\3\1\1\0\7\1\3\0"+
    "\4\1\2\0\6\1\4\0\15\1\5\0\3\1\1\0\7\1\53\0"+
    "\1\16\1\16\107\0\1\1\15\0\1\1\202\0\1\1\4\0\1\1"+
    "\2\0\12\1\1\0\1\1\3\0\5\1\6\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\4\1\1\0\3\1\1\0\7\1\3\0\3\1"+
    "\5\0\5\1\u0ebb\0\2\1\52\0\5\1\5\0\2\1\4\0\126\1"+
    "\6\0\3\1\1\0\132\1\1\0\4\1\5\0\50\1\4\0\136\1"+
    "\21\0\30\1\70\0\20\1\u0200\0\u19b6\1\112\0\u51a6\1\132\0\u048d\1"+
    "\u0773\0\u2ba4\1\u215c\0\u012e\1\2\0\73\1\225\0\7\1\14\0\5\1"+
    "\5\0\1\1\1\0\12\1\1\0\15\1\1\0\5\1\1\0\1\1"+
    "\1\0\2\1\1\0\2\1\1\0\154\1\41\0\u016b\1\22\0\100\1"+
    "\2\0\66\1\50\0\14\1\164\0\5\1\1\0\207\1\23\0\12\2"+
    "\7\0\32\1\6\0\32\1\13\0\131\1\3\0\6\1\2\0\6\1"+
    "\2\0\6\1\2\0\3\1\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\3\1\2\2\2\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\2"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\3\1\2"+
    "\1\1\1\0\1\24\2\1\1\24\1\0\1\25\2\0"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\3\1\0\1\36\2\0\1\37\2\0\1\37\1\25"+
    "\1\3\2\0\3\3\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\344\0\u010a"+
    "\0\46\0\u0130\0\46\0\46\0\46\0\46\0\u0156\0\u017c"+
    "\0\u01a2\0\46\0\46\0\u01c8\0\u01ee\0\u0214\0\46\0\46"+
    "\0\46\0\46\0\u023a\0\u0260\0\u0286\0\u02ac\0\46\0\u02d2"+
    "\0\u02f8\0\u031e\0\u0344\0\u036a\0\u0390\0\u03b6\0\46\0\46"+
    "\0\46\0\46\0\46\0\46\0\46\0\46\0\u03dc\0\u0260"+
    "\0\46\0\u0402\0\u0428\0\46\0\u044e\0\u0474\0\u036a\0\46"+
    "\0\u049a\0\u04c0\0\u04e6\0\u050c\0\u0532\0\u0558\0\114";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\2\3\1\6\1\7"+
    "\1\3\1\10\1\2\1\11\1\4\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\4\3\1\34\47\0\7\3\1\0\1\3\3\0\1\3"+
    "\22\0\5\3\4\0\2\4\2\0\1\35\1\36\1\37"+
    "\3\0\1\4\22\0\1\37\1\0\1\37\6\0\2\40"+
    "\1\41\1\0\1\35\1\36\1\37\3\0\1\40\22\0"+
    "\1\37\1\0\1\37\4\0\6\3\1\6\1\0\1\3"+
    "\3\0\1\3\22\0\5\3\4\0\1\42\1\37\10\0"+
    "\1\42\30\0\12\43\1\44\1\45\1\46\31\43\14\0"+
    "\1\11\55\0\1\47\46\0\1\50\51\0\1\51\45\0"+
    "\1\52\45\0\1\53\1\54\44\0\1\55\1\0\1\56"+
    "\13\0\7\3\1\0\1\3\3\0\1\3\22\0\1\3"+
    "\1\57\3\3\1\0\45\60\1\61\7\0\1\35\41\0"+
    "\1\62\1\63\4\0\1\37\3\0\1\62\22\0\1\37"+
    "\1\0\1\37\6\0\2\40\2\0\1\35\5\0\1\40"+
    "\33\0\2\41\1\0\1\41\1\35\1\0\1\41\3\0"+
    "\1\41\22\0\3\41\6\0\2\42\10\0\1\42\30\0"+
    "\12\46\1\64\33\46\12\0\1\64\33\0\4\43\1\65"+
    "\1\66\4\43\1\67\1\43\1\46\1\65\30\43\12\46"+
    "\1\70\33\46\1\0\7\3\1\0\1\3\3\0\1\3"+
    "\22\0\2\3\1\71\2\3\4\0\2\62\4\0\1\37"+
    "\3\0\1\62\22\0\1\37\1\0\1\37\14\0\1\37"+
    "\26\0\1\37\1\0\1\37\3\0\4\46\1\72\5\46"+
    "\1\64\2\46\1\72\33\46\2\73\1\46\1\73\2\46"+
    "\1\73\1\64\2\46\1\73\22\46\3\73\3\46\1\0"+
    "\7\3\1\0\1\3\3\0\1\3\22\0\3\3\1\74"+
    "\1\3\1\0\4\46\1\43\5\46\1\64\2\46\1\43"+
    "\33\46\2\43\1\46\1\43\2\46\1\43\1\64\2\46"+
    "\1\43\22\46\3\43\3\46\1\0\7\3\1\0\1\3"+
    "\3\0\1\3\22\0\4\3\1\75\2\0\7\3\1\0"+
    "\1\3\3\0\1\3\22\0\1\3\1\76\3\3\2\0"+
    "\7\3\1\0\1\3\3\0\1\3\22\0\1\77\4\3"+
    "\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1406];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\6\1\1\11\1\1\4\11\3\1\2\11"+
    "\3\1\4\11\3\1\1\0\1\11\3\1\1\0\1\1"+
    "\2\0\10\11\1\1\1\0\1\11\2\0\1\11\2\0"+
    "\1\1\1\11\1\1\2\0\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
 	private Symbol symbol( int type ){
		return symbol( type, null );
	}
	private Symbol symbol( int type, String value) {
		return new Symbol( type, value );
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1310) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 18: 
          { return symbol( sym.QUESTION );
          }
        case 33: break;
        case 15: 
          { return symbol( sym.LESS );
          }
        case 34: break;
        case 19: 
          { return symbol( sym.COLON );
          }
        case 35: break;
        case 7: 
          { return symbol( sym.TIMES );
          }
        case 36: break;
        case 24: 
          { return symbol( sym.NEQ );
          }
        case 37: break;
        case 6: 
          { return symbol( sym.MINUS );
          }
        case 38: break;
        case 28: 
          { return symbol( sym.LESS_EQ );
          }
        case 39: break;
        case 29: 
          { return symbol( sym.SHIFT_LEFT );
          }
        case 40: break;
        case 17: 
          { return symbol( sym.CLOSE );
          }
        case 41: break;
        case 31: 
          { return symbol( sym.CHARACTER, yytext() );
          }
        case 42: break;
        case 14: 
          { return symbol( sym.GREATER );
          }
        case 43: break;
        case 30: 
          { return symbol( sym.ERROR, "No strings permitted in condition: " + yytext() );
          }
        case 44: break;
        case 16: 
          { return symbol( sym.OPEN );
          }
        case 45: break;
        case 25: 
          { return symbol( sym.EQ );
          }
        case 46: break;
        case 8: 
          { return symbol( sym.DIVISION );
          }
        case 47: break;
        case 21: 
          { return symbol( sym.ERROR, "Illegal character: " + yytext() );
          }
        case 48: break;
        case 32: 
          { return symbol( sym.DEFINED );
          }
        case 49: break;
        case 2: 
          { return symbol( sym.ERROR, "Unexpected sign in condition: " + yytext() );
          }
        case 50: break;
        case 3: 
          { return symbol( sym.IDENTIFIER, yytext() );
          }
        case 51: break;
        case 9: 
          { return symbol( sym.BIT_OR );
          }
        case 52: break;
        case 10: 
          { return symbol( sym.BIT_AND );
          }
        case 53: break;
        case 23: 
          { return symbol( sym.AND );
          }
        case 54: break;
        case 1: 
          { return symbol( sym.INTEGER, yytext() );
          }
        case 55: break;
        case 13: 
          { return symbol( sym.BIT_REVERSE );
          }
        case 56: break;
        case 27: 
          { return symbol( sym.SHIFT_RIGHT );
          }
        case 57: break;
        case 22: 
          { return symbol( sym.OR );
          }
        case 58: break;
        case 12: 
          { return symbol( sym.XOR );
          }
        case 59: break;
        case 11: 
          { return symbol( sym.NOT );
          }
        case 60: break;
        case 26: 
          { return symbol( sym.GREATER_EQ );
          }
        case 61: break;
        case 20: 
          { return symbol( sym.ERROR, "Floating point number not allowed in condition: " + yytext() );
          }
        case 62: break;
        case 4: 
          { 
          }
        case 63: break;
        case 5: 
          { return symbol( sym.PLUS );
          }
        case 64: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
